apiVersion: apps/v1
kind: Deployment
metadata:
  name: space-invaders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: space-invaders
  template:
    metadata:
      labels:
        app: space-invaders
    spec:
      containers:
      - name: space-invaders
        image: <dein-docker-image-name>  # Ersetze dies mit deinem Docker-Image-Namen
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: space-invaders-service
spec:
  selector:
    app: space-invaders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
